/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes.$recipeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/discover': typeof DiscoverRoute
  '/quick': typeof QuickRoute
  '/saved': typeof SavedRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/discover': typeof DiscoverRoute
  '/quick': typeof QuickRoute
  '/saved': typeof SavedRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/discover': typeof DiscoverRoute
  '/quick': typeof QuickRoute
  '/saved': typeof SavedRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/budget' | '/discover' | '/quick' | '/saved' | '/recipes/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/budget' | '/discover' | '/quick' | '/saved' | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/discover'
    | '/quick'
    | '/saved'
    | '/recipes/$recipeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRoute
  DiscoverRoute: typeof DiscoverRoute
  QuickRoute: typeof QuickRoute
  SavedRoute: typeof SavedRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRoute,
  DiscoverRoute: DiscoverRoute,
  QuickRoute: QuickRoute,
  SavedRoute: SavedRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
